### ISSUE TITLE
debian 11 bullseye > gjs 1.66.2 : no -m option

### ISSUE THREAD

**Issue by PHHENS** [sonnyp/mermaid-webkitgtk#1]
Dear Sonny,
It seems that, on debian 11 bullseye, the gjs package (1.66.2) has no -m option.

Thanks

**Comment by sonnyp** [comment]
gjs 1.66.2 is really tool old for me to care sorry
Even if I didn't use `-m` - I don't want to test the script on a 2.5 years old gjs version.

This won't be a problem anyway with Apostrophe Flatpak.
